exports.getBalance = require("./well-coin/get-balance")
exports.addMember = require("./0-member/add-member")
exports.getAddress = require("./get-address")
exports.sendCoin = require("./well-coin/send-coin")
exports.storeAll = require("./filecoin-market-consumer/store-all")
exports.addWellness = require("./1-dao-actions/add-wellness-info.js")
exports.fund = require("./deal-rewarder/fund")
exports.claimBounty = require("./deal-rewarder/claim-bounty")