[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    "@ds-test/=lib/ds-test/src/",
    "solidity-cborutils/=lib/solidity-cborutils/",
    "@forge-std/=lib/forge-std/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@filecoin/=v0.8"
]
rpc_endpoints = { wallaby = '${WALLABY_RPC_URL}' }
fuzz_runs = 256
